meta_product_name: "Apoyo"
meta_title: "Apoyo - Connecting Businesses and Charities"
meta_description: "Charities are fighting to make the world a better place. It is not an easy task. We at Apoyo wish to help these charities by connecting them with businesses who are only to eager to lend a hand."
meta_image: "ogimage.png"
twitter_account: "@apoyo_twitter_account"
